# Generated by Django 4.2.6 on 2023-10-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllUsers',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=350)),
                ('email', models.CharField(max_length=350, unique=True)),
                ('phone', models.CharField(max_length=11, unique=True)),
                ('state', models.CharField(max_length=122)),
                ('facility', models.CharField(max_length=350)),
                ('usercategory', models.CharField(max_length=65)),
                ('password', models.CharField(blank=True, max_length=364, null=True)),
            ],
            options={
                'db_table': 'all_users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CervicData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(blank=True, max_length=25, null=True)),
                ('age', models.CharField(blank=True, max_length=3, null=True)),
                ('mode', models.CharField(blank=True, max_length=45, null=True)),
                ('image_base64', models.TextField()),
                ('imagetype1', models.CharField(blank=True, max_length=25, null=True)),
                ('aceticacid_base64', models.TextField(blank=True, null=True)),
                ('imagetype2', models.CharField(blank=True, max_length=25, null=True)),
                ('lugolsiodine_base64', models.TextField(blank=True, null=True)),
                ('imagetype3', models.CharField(blank=True, max_length=25, null=True)),
                ('initial_diagnosis', models.CharField(blank=True, max_length=45, null=True)),
                ('initial_diagnosis_other', models.CharField(blank=True, max_length=1000, null=True)),
                ('initial_diagnosis_by', models.CharField(blank=True, max_length=100, null=True)),
                ('final_diagnosis', models.CharField(blank=True, max_length=45, null=True)),
                ('final_diagnosis_other', models.CharField(blank=True, max_length=1000, null=True)),
                ('final_diagnosis_by', models.CharField(blank=True, max_length=125, null=True)),
                ('treatment_options', models.CharField(blank=True, max_length=95, null=True)),
                ('comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('final_diag_comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('timestamp_id', models.CharField(blank=True, max_length=65, null=True)),
                ('state', models.CharField(blank=True, max_length=25, null=True)),
                ('facility', models.CharField(blank=True, max_length=125, null=True)),
                ('date_submitted', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cervic_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CervicTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=30)),
                ('received_treatment', models.CharField(max_length=30)),
                ('date_trtmt_rec', models.DateField(blank=True, null=True)),
                ('reg_date', models.DateTimeField(blank=True, null=True)),
                ('cervic_data_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cervic_treatment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chattabox',
            fields=[
                ('chat_id', models.AutoField(primary_key=True, serialize=False)),
                ('from_user', models.CharField(blank=True, max_length=655, null=True)),
                ('to_user', models.CharField(blank=True, max_length=655, null=True)),
                ('message', models.CharField(blank=True, max_length=350, null=True)),
                ('msg_status', models.CharField(blank=True, max_length=25, null=True)),
                ('chat_timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chattabox',
                'managed': False,
            },
        ),
    ]
